config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsletter.urls', namespace='newsletter')),
] + static(settings.MEDIA_URL, documentroot=settings.MEDIA_ROOT)

newsletter/urls.py
from django.urls import path

from newsletter.apps import NewsletterConfig
from newsletter.views import ClientCreateView, ClientListView, ClientDetailView

app_name = NewsletterConfig.name

urlpatterns = [
    path('', ClientListView.as_view(), name='list_client'),
    path('create_client/', ClientCreateView.as_view(), name='create_client'),
    path('<int:pk>/client_detail/', ClientDetailView.as_view(), name='detail_client'),
]

newsletter/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(models.Model):
    """Модель для пользователя"""
    fio = models.CharField(max_length=150, verbose_name='ФИО пользователя')
    email = models.EmailField(max_length=100, verbose_name='Email')

    def __str__(self):
        return f'Пользователь: {self.fio}, почта: {self.email}'

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class Client(models.Model):
    """Модель клиента"""
    fio = models.CharField(max_length=150, verbose_name='ФИО')
    email = models.EmailField(max_length=100, verbose_name='Email')
    comments = models.TextField(max_length=250, verbose_name="Комментарий")

    def __str__(self):
        return f'Клиент {self.fio}, почта: {self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class LogsForClient(models.Model):
    """Модель для логов"""
    datetime_last_try = models.DateTimeField(verbose_name='дата последней попытки')
    sent_status = models.BooleanField(verbose_name='статус отправки')
    server_response = models.TextField(verbose_name='ответ сервера')

    def __str__(self):
        return f'Ответ сервера - {self.server_response}, статус отправки - {self.sent_status},' \
               f'дата последней попытки {self.datetime_last_try}'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'


class Sending(models.Model):
    """Модель для настройки рассылки"""
    choices_periodic = [{'once_a_day', 'раз в день'},
                        {'once_a_week', 'раз в неделю'},
                        {'once_a_month', 'раз в месяц'}]

    choices_status = [{'created', 'создана'},
                      {'launched', 'запущена'},
                      {'completed', 'завершена'}]

    mailing_time = models.TimeField(verbose_name="Время рассылки")
    periodicity_mailing = models.IntegerField(choices=choices_periodic, verbose_name='Периодичность рассылки')
    message = models.TextField(verbose_name='Сообщение')
    status_mailing = models.CharField(choices=choices_status, default='created', verbose_name='Статус рассылки')
    message_subject = models.CharField(max_length=150, verbose_name='Тема письма')

    def __str__(self):
        return f"Тема сообщения - {self.message_subject}, статус рассылки - {self.status_mailing}."

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

newsletter/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView

from newsletter.models import Sending, Client


class ClientCreateView(CreateView):
    model = Client
    fields = ('fio', 'email', )
    success_url = reverse_lazy('newsletter:list_client')


class ClientListView(ListView):
    model = Client


class ClientDetailView(DetailView):
    model = Client

newsletter/templates/newsletter/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Newsletter</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Newsletter</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'newsletter:create_client' %}">Регистрация</a>
        <a class="p-2 btn btn-outline-primary" href="#">#</a>
        <a class="p-2 btn btn-outline-primary" href="#">#</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
    <p class="lead">NewsLetter - это лучший сервис для управления рассылками!</p>
</div>

<div class="container">
    {% block content %}
    {% endblock%}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Newsletter
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

newsletter/templates/newsletter/client_detail.html
{% extends 'newsletter/base.html' %}
{% load static %}

{% block content %}
<div class="card" style="width: 18rem;">
    <div class="card-body">
        <h4 class="card-title">{{ object.fio }}</h4>
        <p class="card-text">{{ object.email }}</p>
    </div>
    <div class="card-body">
        <a href="#" type="button" class="btn btn-lg btn-block btn-outline-primary">Редактировать</a>
    </div>
    <div class="card-body">
        <a href="#" type="button" class="btn btn-lg btn-block btn-outline-primary">Удалить</a>
    </div>
</div>
{% endblock %}

newsletter/templates/newsletter/client_form.html
{% extends 'newsletter/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-3">
        <div class="card">
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
            </div>
        </div>
        <button type="submit" class="btn btn-success">
            {% if object %}
            Сохранить
            {% else %}
            Создать
            {% endif %}
        </button>
    </div>
</form>
{% endblock %}

newsletter/templates/newsletter/client_list.html
{% extends 'newsletter/base.html' %}

{% block content %}
<div class="row text-center">
    <p>Клиенты, которые нам доверяют</p>
    {% for object in object_list %}
        {% include 'newsletter/includes/inc_base_category.html' %}
    {% endfor %}
</div>
{% endblock %}

newsletter/templates/newsletter/includes/inc_base_category.html
<div class="col-3 ">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.fio }}</h4>
        </div>
        <div class="card-body">
            <a href="{% url 'newsletter:detail_client' object.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Перейти</a>
        </div>
    </div>
</div>